channels:
  - defaults
dependencies:
  - pip
  - pip:
    - albumentations
    - dill
    - einops
    - ftfy
    - h5py
    - matplotlib
    - numpy
    - nltk
    - omegaconf
    - pandas
    - pillow
    - pip
    - pyflakes
    - pytorch_lightning
    - regex
    - scikit-image
    - seaborn
    - tensorflow
    - tokenizers
    - torch
    - torchvision
    - tqdm
    - transformers
    - typing_extensions
    - wandb
    - wrapt